package httpx

const (
	ParamCLI    = "cli"
	ParamJWT    = "jwt"
	ParamOrigin = "origin"
)

const (
	HeaderAccept                    = "Accept"
	HeaderAccessControlAllowHeaders = "Access-Control-Allow-Headers"
	HeaderAccessControlAllowMethods = "Access-Control-Allow-Methods"
	HeaderAccessControlAllowOrigin  = "Access-Control-Allow-Origin"
	HeaderAuthorization             = "Authorization"
	HeaderCSRFToken                 = "X-CSRF-Token"
	HeaderCacheControl              = "Cache-Control"
	HeaderContentDisposition        = "Content-Disposition"
	HeaderContentEncoding           = "Content-Encoding"
	HeaderContentLanguage           = "Content-Language"
	HeaderContentLength             = "Content-Length"
	HeaderContentLocation           = "Content-Location"
	HeaderContentMD5                = "Content-MD5"
	HeaderContentRange              = "Content-Range"
	HeaderContentType               = "Content-Type"
	HeaderCookie                    = "Cookie"
	HeaderCrossOriginEmbedderPolicy = "Cross-Origin-Embedder-Policy"
	HeaderCrossOriginOpenerPolicy   = "Cross-Origin-Opener-Policy"
	HeaderCrossOriginResourcePolicy = "Cross-Origin-Resource-Policy"
	HeaderCustomCommand             = "X-Command"
	HeaderETag                      = "ETag"
	HeaderExpires                   = "Expires"
	HeaderHxRedirect                = "HX-Redirect"
	HeaderHxRefresh                 = "HX-Refresh"
	HeaderHxRequest                 = "HX-Request"
	HeaderHxRetarget                = "HX-Retarget"
	HeaderIfModifiedSince           = "If-Modified-Since"
	HeaderLastModified              = "Last-Modified"
	HeaderLocation                  = "Location"
	HeaderUserAgent                 = "User-Agent"
	HeaderXDeployID                 = "X-Deploy-ID"
	HeaderXDeployLabel              = "X-Deploy-Label"
	HeaderXDeployPassword           = "X-Deploy-Password"
	HeaderXDeployPinned             = "X-Deploy-Pinned"
	HeaderXForwardedFor             = "X-Forwarded-For"
	HeaderXForwardedHost            = "X-Forwarded-Host"
	HeaderXForwardedPrefix          = "X-Forwarded-Prefix"
	HeaderXForwardedProto           = "X-Forwarded-Proto"
	HeaderXFrameOptions             = "X-Frame-Options"
)

const (
	ContentTypeBytes      = "application/octet-stream"
	ContentTypeCSS        = "text/css"
	ContentTypeForm       = "application/x-www-form-urlencoded"
	ContentTypeGzip       = "application/gzip"
	ContentTypeHTML       = "text/html"
	ContentTypeJavascript = "text/javascript"
	ContentTypeJSON       = "application/json"
	ContentTypeMarkdown   = "text/markdown"
	ContentTypePdf        = "application/pdf"
	ContentTypePng        = "image/png"
	ContentTypeText       = "text/plain"
	ContentTypeTextUtf8   = "text/plain; charset=utf-8"
	ContentTypeWasm       = "application/wasm"
	ContentTypeXML        = "text/xml"
)
